secretGenerator:
- name: mysql-env
  literals:
  - password= #root 패스워드 값

resources:
  - mysql/pvc/mysql-pvc.yaml
  - mysql/statefulset/mysql-sts.yaml
  - mysql/service/mysql-service.yaml
  - mysql/service/mysql-svc-headless.yaml
  - mysql/statefulset/mysql-sts-read.yaml
  - mysql/service/mysql-svc-read.yaml
  - mysql/service/mysql-svc-read-headless.yaml
